
spring:
  datasource:
    url: jdbc:h2:mem:market
    username: admin
    password: admin123
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

springdoc:
  swagger-ui:
    path: swagger-ui
  api-docs:
    path: /api-docs

server:
 tomcat:
   relaxed-query-chars: ['[',']','<','>','`']